# File format documentation at https://goreleaser.com
project_name: hvrt
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: hvrt
    targets:
      # Although we use "github.com/uptrace/bun/driver/sqliteshim" and can
      # support many more targets than those listed below, we only automatically
      # build for systems supported by "modernc.org/sqlite" to avoid dealing
      # with CGO when using goreleaser.
      # See supported platforms of "modernc.org/sqlite" here:
      #   https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures

      # We choose the lowest possible versions of all archs to ensure as broad
      # of support as possible.
      - darwin_amd64_v1
      - darwin_arm64
      - freebsd_amd64_v1
      - freebsd_arm64
      - linux_386_softfloat
      - linux_amd64_v1
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - linux_riscv64
      - windows_amd64_v1
      - windows_arm64
archives:
  # create tar.gz files for every OS except Windows
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# Make macOS binaries universal
universal_binaries:
  - replace: true
