# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: hvrt
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/hvrt
    binary: hvrt
    targets:
      # Based on supported platforms of SQLite module we depend on:
      #   https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures
      - darwin_amd64_v1
      - darwin_arm64
      - freebsd_amd64_v1
      - linux_386
      - linux_amd64_v1
      - linux_arm
      - linux_arm64
      - linux_riscv64
      - windows_amd64_v1
      - windows_arm64
archives:
  - replacements:
      windows: Windows
      darwin: macOS
      linux: Linux
      freebsd: FreeBSD
      openbsd: OpenBSD
      netbsd: NetBSD
      386: "i386"
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# Make macOS binaries universal
universal_binaries:
  - replace: true
