# Docs:
# - https://docs.codecov.com/docs/codecov-yaml
# - https://docs.codecov.com/docs/codecovyml-reference
codecov:
  require_ci_to_pass: false
  max_report_age: false
  notify:
    wait_for_ci: false
