name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test_coverage:
    runs-on: ubuntu-22.04
    name: Coverage report
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Install kcov
        run: sudo apt-get install kcov -y
      - name: Run tests with coverage report
        run: zig build test --summary all -Dreport-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hvrt-vcs/hvrt
          directory: ./zig-out/kcov-out
          fail_ci_if_error: true
          verbose: true
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm, windows-11-arm]
    runs-on: ${{matrix.os}}
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Run tests
        run: zig build test --summary all
