name: Build and test Havarti using Zig
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  # TODO: add a build task for compiling multiple targets. Name it `all`.
  build_all:
    runs-on: ubuntu-latest
    name: Build all cross compile targets
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - run: zig build
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - run: zig build test
